export const ActionTypes = {
  //AUTH HANDLER
  HANDLE_AUTH_IN: 'HANDLE_AUTH_IN',
  HANDLE_AUTH_OUT: 'HANDLE_AUTH_OUT',

  //BURGER HANDLER
  HANDLE_BURGER_TOGGLE: 'HANDLE_BURGER_TOGGLE',

  //CREATE MODAL
  CREATE_MODAL_OPEN: 'CREATE_MODAL_OPEN',
  CREATE_MODAL_CLOSE: 'CREATE_MODAL_CLOSE',

  //DRAG AND DROP
  DRAG_HAPPENED: 'DRAG_HAPPENED',

  //SESSION TYPE
  SIGN_UP_REQUEST: 'session/SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'session/SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'session/SIGN_UP_ERROR',
  SIGN_IN_REQUEST: 'session/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'session/SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'session/SIGN_IN_ERROR',
  REFRESH_USER_REQUEST: 'session/REFRESH_USER_REQUEST',
  REFRESH_USER_SUCCESS: 'session/REFRESH_USER_SUCCESS',
  REFRESH_USER_ERROR: 'session/REFRESH_USER_ERROR',
  LOGOUT_REQUEST: 'session/LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'session/LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'session/LOGOUT_ERROR',
  CLEAR_ERROR_MESSAGE: 'session/CLEAR_ERROR_MESSAGE',
};