export const ActionType = {
  //MODAL HANDLER
  HANDLE_MODAL_OPEN: 'HANDLE_MODAL_OPEN',
  HANDLE_MODAL_CLOSE: 'HANDLE_MODAL_CLOSE',

  //BURGER HANDLER
  HANDLE_BURGER_TOGGLE: 'HANDLE_BURGER_TOGGLE',
};